### ISSUE TITLE
Ease of first run

### ISSUE THREAD

**Issue by jeprecated** [unmonoqueteclea/voilib#1]
Very nice demo, I would love to play around with it. But I have a few issues around the ease to set things up.

Really my main issue is the docker-compose files you offer (https://github.com/unmonoqueteclea/voilib/blob/main/infra/development/compose.yml) and the fact that one must build the app from dev. Here are a few points, which are all kind of connected, on that front:

1. It is rather cumbersome to have to pull the repo and build the docker images myself. Any chance you could push them to a container registry, like dockerhub? 
  - Sub point: why is there a node_modules volume in the frontend? 🤔 the frontend dockerfile seems to run `npm install` so is there a need for it? Anyways this just further hooks the app to the dev setup. It would be best if the containers were as self _contained_ as possible 😅 
2. I only want to run this locally for my own purposes, so I don't need/want traefik. But there's a lot of setup in the other parts 😅 
3. I already run my own instance of Redis. It's easy enough to remove Redis from the compose, but I just bring that one up too to demonstrate that you're offering a big package of everything working together in one docker-compose (plus the dev install). Which is great! But not what lots of devs need 😅 which are the exact type of people who will try and play around with this.

**Comment by unmonoqueteclea** [comment]
Thank you very much for your feedback, Jordan!

I fully agree with you, thank you for helping me to identify the problem :) 
I think I missed a use case. I was thinking about two kinds of users:

- The user that is going to **develop** something on top of Voilib (dev setup)
- The user that wants to **deploy** her own version of Voilib on a public url to be consumed by a group of people (prod setup)

And I think I forgot about users that just want to self host Voilib, running locally, for personal use! Let me think a little bit about how I can help those users. It's funny because I am, actually, one of those users that self host things like Home Assistant (for home automation) or Umami (for web analytics)

I hope to have great news related to this issue soon (hopefully, in less than a month)

**Comment by jeprecated** [comment]
No worries, mate. Thanks for the positive response 👏 I look forward to playing around with it, whenever you get around to making whatever changes you like 👍

**Comment by unmonoqueteclea** [comment]
Hey @ohare93 (and everybody)! After a long time... I've just released `v3.0.0` that allows you to run Voilib with just these commands:

```bash
mkdir voilib && cd "voilib"
curl https://raw.githubusercontent.com/unmonoqueteclea/voilib/main/compose.yml -o compose.yml
docker compose up
```

🥳🥳🥳🥳

Now, we have even a UI for management tasks!

![Management](https://github.com/unmonoqueteclea/voilib/raw/main/docs/management.png)

**Comment by unmonoqueteclea** [comment]
So.... I think we can now close this :)

Feel free to open new issues if needed. Looking forward for receiving your feedback!!

**Comment by jeprecated** [comment]
Excellent! I’ll give it a whirl soon 👍 thanks for the efforts, mate
